# Generated by Django 5.1.5 on 2025-01-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPatern', models.CharField(max_length=50)),
                ('apellidoMatern', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=50)),
                ('departamento', models.CharField(max_length=50)),
            ],
        ),
    ]
