# Generated by Django 5.1.5 on 2025-01-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, default='/secondproject/empleados/empleado_defaul.png', null=True, upload_to='empleados', verbose_name='Imagen'),
        ),
    ]
