# Generated by Django 5.1.5 on 2025-01-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empleado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, default='media/empleados/empleado_defaul.png', null=True, upload_to='media/empleados', verbose_name='Imagen'),
        ),
    ]
