# Generated by Django 5.1.5 on 2025-01-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_alter_empleado_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, default='empleados/empleadodefaul.png', null=True, upload_to='empleados', verbose_name='Imagen'),
        ),
    ]
